plugins:

  tf:
    executor: central_deployment_agent
    package_name: cloudify-terraform-plugin
    package_version: '0.1.dev0'
    source: https://github.com/earthmant/cloudify-terraform-plugin/archive/7fd446f886315351d5189453b06648b14c674848.zip

data_types:

  cloudify.types.terraform.RootModule:
    properties:
      source:
        type: string
        description: The path to a resource packaged relative to the blueprint YAML.
        required: true

node_types:

  cloudify.nodes.terraform.Module:
    properties:
      resource_config:
        type: cloudify.types.terraform.RootModule
    interfaces:
      cloudify.interfaces.lifecycle:
        create: {}
        configure:
          implementation: tf.cloudify_tf.tasks.configure
          inputs:
            resource_config:
              default: { get_property: [ SELF, resource_config ] }
        start: {}
        stop: {}
        delete: {}
      cloudify.interfaces.validation:
        creation: {}
        deletion: {}
      cloudify.interfaces.monitoring:
        start: {}
        stop: {}
