plugins:

  tf:
    executor: central_deployment_agent
    package_name: cloudify-terraform-plugin

data_types:

  cloudify.types.terraform.RootModule:
    properties:
      source:
        type: string
        description: The path to a resource packaged relative to the blueprint YAML.
        required: true
      variables:
        description: A dictionary of variables.
        default: {}
      environment_variables:
        description: A dictionary of environment variables.
        default: {}

node_types:

  cloudify.nodes.terraform.Module:
    properties:
      resource_config:
        type: cloudify.types.terraform.RootModule
    interfaces:
      cloudify.interfaces.lifecycle:
        create: {}
        configure:
          implementation: tf.cloudify_tf.tasks.configure
          inputs:
            resource_config:
              default: { get_property: [ SELF, resource_config ] }
        start: {}
        stop: {}
        delete: {}
      cloudify.interfaces.validation:
        creation: {}
        deletion: {}
      cloudify.interfaces.monitoring:
        start: {}
        stop: {}
